variables:
  IOS_XCODE_PROJECT_NAME: "Runner"
  FLAVOR: "production"

stages:
  - test
  - build
  - deploy

dev_test:
  image: cirrusci/flutter
  stage: test
  tags:
    - flutter
    #- flutter-runner
    #- 2f-flutter-ssh
  before_script:
    - flutter clean
  script:
    - flutter pub get
    - flutter doctor --android-licenses
    - flutter test
  artifacts:
    expire_in: 1 day

android:debug:
  image: cirrusci/flutter
  stage: build
  tags:
    - flutter
    #- flutter-runner
    #- 2f-flutter-ssh
  script:
    - flutter doctor --android-licenses
    - flutter build apk --debug
  artifacts:
    paths:
      - "**/**/**/**/**/**/*.apk"
    expire_in: 1 day

  only:
      refs:
          - dev

android:release:
  image: cirrusci/flutter
  stage: build
  tags:
    - flutter
    #- flutter-runner
    #- 2f-flutter-ssh
  script:
    - flutter doctor --android-licenses
    - flutter build apk --release
  artifacts:
    paths:
      - "**/**/**/**/**/**/*.apk"
    expire_in: 1 day

  only:
      refs:
          - main

