name: lastmile_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # hive for local storage
  hive: ^2.2.3
  path_provider: ^2.0.11

  # google map
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0

  # geo locator for tracking user location
  geolocator: ^9.0.2

  # equitable for comparing objects
  equatable: ^2.0.5

  # Get it for dependency issue
  get_it: ^7.2.0

  # permission handler
  permission_handler: ^10.2.0

  # flutter bloc for state management
  flutter_bloc: ^8.1.1

  # dio for http calls
  dio: ^4.0.6

  # dartz for managing data state
  dartz: ^0.10.1

  # colors, ui, icons, utils, fonts and more...
  cupertino_icons: ^1.0.2
  shimmer:
  infinite_scroll_pagination:
  internet_connection_checker:
  flutter_phosphor_icons:
  flutter_native_splash: ^2.2.14
  socket_io_client: ^1.0.2
  bloc_test:
  flutter_slidable: ^2.0.0
  dotted_line: ^3.1.0
  url_launcher: ^6.1.6
  pinput: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  network_image_mock:
  build_runner:
  bdd_widget_test:
  change_app_package_name: ^1.1.0
  hive_generator: ^1.1.2

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
