// Mocks generated by Mockito 5.3.2 from annotations
// in lastmile_mobile/test/utils/test_injector.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:bloc/bloc.dart' as _i16;
import 'package:dartz/dartz.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i12;
import 'package:lastmile_mobile/src/core/params/request_params.dart' as _i21;
import 'package:lastmile_mobile/src/core/resources/failure.dart' as _i14;
import 'package:lastmile_mobile/src/data/datasources/local/app_hive_service.dart'
    as _i8;
import 'package:lastmile_mobile/src/data/models/driver.dart' as _i22;
import 'package:lastmile_mobile/src/data/models/order.dart' as _i15;
import 'package:lastmile_mobile/src/data/repositories/app_hive_repository.dart'
    as _i18;
import 'package:lastmile_mobile/src/data/repositories/auth_repo_impl.dart'
    as _i20;
import 'package:lastmile_mobile/src/data/repositories/base_location_repo_impl.dart'
    as _i10;
import 'package:lastmile_mobile/src/data/repositories/image_upload_repo_impl.dart'
    as _i19;
import 'package:lastmile_mobile/src/data/repositories/order_history_repo_impl.dart'
    as _i13;
import 'package:lastmile_mobile/src/presentation/views/home_page/blocs/driver_location/driver_location_bloc.dart'
    as _i3;
import 'package:lastmile_mobile/src/presentation/views/home_page/blocs/socket/socket_bloc.dart'
    as _i6;
import 'package:lastmile_mobile/src/presentation/views/home_page/blocs/update_location/update_location_bloc.dart'
    as _i7;
import 'package:lastmile_mobile/src/presentation/views/registration_page/bloc/blocs/image_upload/image_upload_bloc.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:socket_io_client/socket_io_client.dart' as _i5;
import 'package:socket_io_client/src/manager.dart' as _i4;
import 'package:socket_io_common/src/util/event_emitter.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriverLocationState_1 extends _i1.SmartFake
    implements _i3.DriverLocationState {
  _FakeDriverLocationState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManager_2 extends _i1.SmartFake implements _i4.Manager {
  _FakeManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocket_3 extends _i1.SmartFake implements _i5.Socket {
  _FakeSocket_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocketState_4 extends _i1.SmartFake implements _i6.SocketState {
  _FakeSocketState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateLocationState_5 extends _i1.SmartFake
    implements _i7.UpdateLocationState {
  _FakeUpdateLocationState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppHiveService_6 extends _i1.SmartFake
    implements _i8.AppHiveService {
  _FakeAppHiveService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageUploadState_7 extends _i1.SmartFake
    implements _i9.ImageUploadState {
  _FakeImageUploadState_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GeoLocationRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoLocationRepositoryImpl extends _i1.Mock
    implements _i10.GeoLocationRepositoryImpl {
  @override
  _i11.Stream<_i12.Position?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i11.Stream<_i12.Position?>.empty(),
        returnValueForMissingStub: _i11.Stream<_i12.Position?>.empty(),
      ) as _i11.Stream<_i12.Position?>);
}

/// A class which mocks [OrderHistoryRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderHistoryRepoImpl extends _i1.Mock
    implements _i13.OrderHistoryRepoImpl {
  @override
  _i11.Future<
      _i2
          .Either<_i14.Failure, List<_i15.OrderModel>>> getOrderHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderHistory,
          [],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i14.Failure, List<_i15.OrderModel>>>.value(
                _FakeEither_0<_i14.Failure, List<_i15.OrderModel>>(
          this,
          Invocation.method(
            #getOrderHistory,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Either<_i14.Failure, List<_i15.OrderModel>>>.value(
                _FakeEither_0<_i14.Failure, List<_i15.OrderModel>>(
          this,
          Invocation.method(
            #getOrderHistory,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i14.Failure, List<_i15.OrderModel>>>);
}

/// A class which mocks [DriverLocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverLocationBloc extends _i1.Mock
    implements _i3.DriverLocationBloc {
  @override
  _i3.DriverLocationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeDriverLocationState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeDriverLocationState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.DriverLocationState);
  @override
  _i11.Stream<_i3.DriverLocationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i3.DriverLocationState>.empty(),
        returnValueForMissingStub: _i11.Stream<_i3.DriverLocationState>.empty(),
      ) as _i11.Stream<_i3.DriverLocationState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void add(_i3.DriverLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i3.DriverLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.DriverLocationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i3.DriverLocationEvent>(
    _i16.EventHandler<E, _i3.DriverLocationState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i16.Transition<_i3.DriverLocationEvent, _i3.DriverLocationState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i16.Change<_i3.DriverLocationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Socket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocket extends _i1.Mock implements _i5.Socket {
  @override
  String get nsp => (super.noSuchMethod(
        Invocation.getter(#nsp),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set nsp(String? _nsp) => super.noSuchMethod(
        Invocation.setter(
          #nsp,
          _nsp,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set opts(Map<dynamic, dynamic>? _opts) => super.noSuchMethod(
        Invocation.setter(
          #opts,
          _opts,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Manager get io => (super.noSuchMethod(
        Invocation.getter(#io),
        returnValue: _FakeManager_2(
          this,
          Invocation.getter(#io),
        ),
        returnValueForMissingStub: _FakeManager_2(
          this,
          Invocation.getter(#io),
        ),
      ) as _i4.Manager);
  @override
  set io(_i4.Manager? _io) => super.noSuchMethod(
        Invocation.setter(
          #io,
          _io,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Socket get json => (super.noSuchMethod(
        Invocation.getter(#json),
        returnValue: _FakeSocket_3(
          this,
          Invocation.getter(#json),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.getter(#json),
        ),
      ) as _i5.Socket);
  @override
  set json(_i5.Socket? _json) => super.noSuchMethod(
        Invocation.setter(
          #json,
          _json,
        ),
        returnValueForMissingStub: null,
      );
  @override
  num get ids => (super.noSuchMethod(
        Invocation.getter(#ids),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as num);
  @override
  set ids(num? _ids) => super.noSuchMethod(
        Invocation.setter(
          #ids,
          _ids,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<dynamic, dynamic> get acks => (super.noSuchMethod(
        Invocation.getter(#acks),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  set acks(Map<dynamic, dynamic>? _acks) => super.noSuchMethod(
        Invocation.setter(
          #acks,
          _acks,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get connected => (super.noSuchMethod(
        Invocation.getter(#connected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set connected(bool? _connected) => super.noSuchMethod(
        Invocation.setter(
          #connected,
          _connected,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get disconnected => (super.noSuchMethod(
        Invocation.getter(#disconnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set disconnected(bool? _disconnected) => super.noSuchMethod(
        Invocation.setter(
          #disconnected,
          _disconnected,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<dynamic> get sendBuffer => (super.noSuchMethod(
        Invocation.getter(#sendBuffer),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);
  @override
  set sendBuffer(List<dynamic>? _sendBuffer) => super.noSuchMethod(
        Invocation.setter(
          #sendBuffer,
          _sendBuffer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<dynamic> get receiveBuffer => (super.noSuchMethod(
        Invocation.getter(#receiveBuffer),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);
  @override
  set receiveBuffer(List<dynamic>? _receiveBuffer) => super.noSuchMethod(
        Invocation.setter(
          #receiveBuffer,
          _receiveBuffer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set query(String? _query) => super.noSuchMethod(
        Invocation.setter(
          #query,
          _query,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set subs(List<dynamic>? _subs) => super.noSuchMethod(
        Invocation.setter(
          #subs,
          _subs,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set flags(Map<dynamic, dynamic>? _flags) => super.noSuchMethod(
        Invocation.setter(
          #flags,
          _flags,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  void subEvents() => super.noSuchMethod(
        Invocation.method(
          #subEvents,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Socket open() => (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #open,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #open,
            [],
          ),
        ),
      ) as _i5.Socket);
  @override
  _i5.Socket connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #connect,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #connect,
            [],
          ),
        ),
      ) as _i5.Socket);
  @override
  _i5.Socket send(List<dynamic>? args) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [args],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #send,
            [args],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #send,
            [args],
          ),
        ),
      ) as _i5.Socket);
  @override
  void emit(
    String? event, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #emit,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitWithBinary(
    String? event, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #emitWithBinary,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitWithAck(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitWithAck,
          [
            event,
            data,
          ],
          {
            #ack: ack,
            #binary: binary,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #packet,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onopen([dynamic _]) => super.noSuchMethod(
        Invocation.method(
          #onopen,
          [_],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onclose(dynamic reason) => super.noSuchMethod(
        Invocation.method(
          #onclose,
          [reason],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onpacket(dynamic packet) => super.noSuchMethod(
        Invocation.method(
          #onpacket,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onevent(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onevent,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  Function ack(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #ack,
          [id],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as Function);
  @override
  void onack(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onack,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onconnect() => super.noSuchMethod(
        Invocation.method(
          #onconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitBuffered() => super.noSuchMethod(
        Invocation.method(
          #emitBuffered,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void ondisconnect() => super.noSuchMethod(
        Invocation.method(
          #ondisconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void destroy() => super.noSuchMethod(
        Invocation.method(
          #destroy,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Socket close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #close,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #close,
            [],
          ),
        ),
      ) as _i5.Socket);
  @override
  _i5.Socket disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        ),
      ) as _i5.Socket);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Socket compress(dynamic compress) => (super.noSuchMethod(
        Invocation.method(
          #compress,
          [compress],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #compress,
            [compress],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.method(
            #compress,
            [compress],
          ),
        ),
      ) as _i5.Socket);
  @override
  void on(
    String? event,
    _i17.EventHandler<dynamic>? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void once(
    String? event,
    _i17.EventHandler<dynamic>? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #once,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void off(
    String? event, [
    _i17.EventHandler<dynamic>? handler,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #off,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearListeners() => super.noSuchMethod(
        Invocation.method(
          #clearListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool hasListeners(String? event) => (super.noSuchMethod(
        Invocation.method(
          #hasListeners,
          [event],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [SocketBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketBloc extends _i1.Mock implements _i6.SocketBloc {
  @override
  _i6.SocketState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSocketState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSocketState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.SocketState);
  @override
  _i11.Stream<_i6.SocketState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i6.SocketState>.empty(),
        returnValueForMissingStub: _i11.Stream<_i6.SocketState>.empty(),
      ) as _i11.Stream<_i6.SocketState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void add(_i6.SocketEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i6.SocketEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i6.SocketState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i6.SocketEvent>(
    _i16.EventHandler<E, _i6.SocketState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i16.Transition<_i6.SocketEvent, _i6.SocketState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i16.Change<_i6.SocketState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UpdateLocationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateLocationBloc extends _i1.Mock
    implements _i7.UpdateLocationBloc {
  @override
  _i5.Socket get socket => (super.noSuchMethod(
        Invocation.getter(#socket),
        returnValue: _FakeSocket_3(
          this,
          Invocation.getter(#socket),
        ),
        returnValueForMissingStub: _FakeSocket_3(
          this,
          Invocation.getter(#socket),
        ),
      ) as _i5.Socket);
  @override
  _i7.UpdateLocationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUpdateLocationState_5(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUpdateLocationState_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i7.UpdateLocationState);
  @override
  _i11.Stream<_i7.UpdateLocationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i7.UpdateLocationState>.empty(),
        returnValueForMissingStub: _i11.Stream<_i7.UpdateLocationState>.empty(),
      ) as _i11.Stream<_i7.UpdateLocationState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void add(_i7.UpdateLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i7.UpdateLocationEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i7.UpdateLocationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i7.UpdateLocationEvent>(
    _i16.EventHandler<E, _i7.UpdateLocationState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i16.Transition<_i7.UpdateLocationEvent, _i7.UpdateLocationState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void onChange(_i16.Change<_i7.UpdateLocationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppHiveRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppHiveRepositoryImpl extends _i1.Mock
    implements _i18.AppHiveRepositoryImpl {
  @override
  _i8.AppHiveService get hiveService => (super.noSuchMethod(
        Invocation.getter(#hiveService),
        returnValue: _FakeAppHiveService_6(
          this,
          Invocation.getter(#hiveService),
        ),
        returnValueForMissingStub: _FakeAppHiveService_6(
          this,
          Invocation.getter(#hiveService),
        ),
      ) as _i8.AppHiveService);
  @override
  set hiveService(_i8.AppHiveService? _hiveService) => super.noSuchMethod(
        Invocation.setter(
          #hiveService,
          _hiveService,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> putData(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  dynamic getData(String? key) => super.noSuchMethod(
        Invocation.method(
          #getData,
          [key],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImageUploadRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageUploadRepoImpl extends _i1.Mock
    implements _i19.ImageUploadRepoImpl {
  @override
  _i11.Future<_i2.Either<_i14.Failure, String>> uploadImage(
          String? imageFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [imageFilePath],
        ),
        returnValue: _i11.Future<_i2.Either<_i14.Failure, String>>.value(
            _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFilePath],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Either<_i14.Failure, String>>.value(
                _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFilePath],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i14.Failure, String>>);
}

/// A class which mocks [ImageUploadBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageUploadBloc extends _i1.Mock implements _i9.ImageUploadBloc {
  @override
  _i9.ImageUploadState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeImageUploadState_7(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeImageUploadState_7(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.ImageUploadState);
  @override
  _i11.Stream<_i9.ImageUploadState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i9.ImageUploadState>.empty(),
        returnValueForMissingStub: _i11.Stream<_i9.ImageUploadState>.empty(),
      ) as _i11.Stream<_i9.ImageUploadState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void add(_i9.ImageUploadEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i9.ImageUploadEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i9.ImageUploadState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i9.ImageUploadEvent>(
    _i16.EventHandler<E, _i9.ImageUploadState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i16.Transition<_i9.ImageUploadEvent, _i9.ImageUploadState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void onChange(_i16.Change<_i9.ImageUploadState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoImpl extends _i1.Mock implements _i20.AuthRepoImpl {
  @override
  _i11.Future<_i2.Either<_i14.Failure, String>> registerDriver(
          _i21.RegisterDriverRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerDriver,
          [params],
        ),
        returnValue: _i11.Future<_i2.Either<_i14.Failure, String>>.value(
            _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #registerDriver,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Either<_i14.Failure, String>>.value(
                _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #registerDriver,
            [params],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i14.Failure, String>>);
  @override
  _i11.Future<_i2.Either<String, String>> verifyPhoneNumber(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [code],
        ),
        returnValue: _i11.Future<_i2.Either<String, String>>.value(
            _FakeEither_0<String, String>(
          this,
          Invocation.method(
            #verifyPhoneNumber,
            [code],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Either<String, String>>.value(
                _FakeEither_0<String, String>(
          this,
          Invocation.method(
            #verifyPhoneNumber,
            [code],
          ),
        )),
      ) as _i11.Future<_i2.Either<String, String>>);
  @override
  _i11.Future<_i2.Either<_i14.Failure, _i22.DriverModel>> loginDriver(
          String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginDriver,
          [phoneNumber],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i14.Failure, _i22.DriverModel>>.value(
                _FakeEither_0<_i14.Failure, _i22.DriverModel>(
          this,
          Invocation.method(
            #loginDriver,
            [phoneNumber],
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.Either<_i14.Failure, _i22.DriverModel>>.value(
                _FakeEither_0<_i14.Failure, _i22.DriverModel>(
          this,
          Invocation.method(
            #loginDriver,
            [phoneNumber],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i14.Failure, _i22.DriverModel>>);
}
